# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys, os
import shutil
import nodes

def SilentMkdir(theDir):
	try:
		os.mkdir(theDir)
	except:
		pass
	return 0

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(452, 429)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 10, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(btn1_click)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 452, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))

def btn1_click():
    print("click");
    baseDir = "D:\\Diplom\\Diplom\\Diplom"
    srcImageDir = "D:\\Diplom\\Diplom\\image_test\\my5"
    binDir = "D:\\Meshroom-2019.2.0\\aliceVision\\bin"
    numImages = 5

    nodes.Run_00_CameraInit(baseDir, binDir, srcImageDir)
    nodes.Run_01_FeatureExtraction(baseDir, binDir, numImages)
    nodes.Run_02_ImageMatching(baseDir, binDir)
    nodes.Run_03_FeatureMatching(baseDir, binDir)
    nodes.Run_04_StructureFromMotion(baseDir, binDir)
    nodes.Run_05_PrepareDenseScene(baseDir, binDir)

    nodes.Run_06_CameraConnection(baseDir, binDir)

    nodes.Run_07_DepthMap(baseDir, binDir, numImages, 3)
    nodes.Run_08_DepthMapFilter(baseDir, binDir)
    nodes.Run_09_Meshing(baseDir, binDir)
    nodes.Run_10_MeshFiltering(baseDir, binDir)

    nodes.Run_11_Texturing(baseDir, binDir)

    return 0


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
